# -*- coding: utf-8 -*-
"""aula_01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13hmfxlwN1F5DA8rmw6Lp5C0FDmlX5XKD
"""

import pandas as pd
url_dados = 'https://github.com/alura-cursos/imersaodados3/blob/main/dados/dados_experimentos.zip?raw=true'
dados = pd.read_csv(url_dados, compression='zip')#compression para abrir um arquivo zip

dados

dados.head() #mostrar as 5 primeiras linhas.

dados.shape#retorna numero de linhas e colunas

#selcionar apenas uma coluna;
dados['tratamento'].unique() #unique mostra os dados categóricos quais os tipos que estão presente.

dados['tempo'].unique()

dados['dose'].unique()

dados['droga'].unique()

dados['g-0'].unique()

dados['tratamento'].value_counts() # conta os valores dentro da coluna. uma com a quantidade de frequencia que aparece de tratamento com droga e com controle

dados['dose'].value_counts()

dados['tratamento'].value_counts(normalize = True) # os dados voltam normalizados, ou seja, porcentagem.

dados['dose'].value_counts(normalize = True)

dados['tratamento'].value_counts().plot.pie()#visualizando com gráfico

dados['tempo'].value_counts().plot.bar()

dados_filtrados = dados[dados['g-0']>0]
print(dados_filtrados)

agrupados = dados.groupby(['droga']).size()
agrupados