# -*- coding: utf-8 -*-
"""aula_02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vxW1K2tsu16vz_-7yK46_s1fJZDYofXf
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

url_dados = 'https://github.com/alura-cursos/imersaodados3/blob/main/dados/dados_experimentos.zip?raw=true'
dados = pd.read_csv(url_dados, compression='zip')#compression para abrir um arquivo zip

mapa = {
    'droga' : 'composto'
}
dados.rename(columns=mapa, inplace=True)

dados.head()

compostos = dados['composto'].value_counts()[0:5]
cod_compostos = compostos.index #volta somente os indexes sem os valores
cod_compostos
compostos

dados.query('composto in @cod_compostos')# @ usado para avisar que é uma variavel
sns.set()
plt.figure(figsize=(8,6))
sns.countplot(x = 'composto',data=dados.query('composto in @cod_compostos')).set_title('Top 5 Compostos')# Gráfico de barras com contagem.
plt.show()

len(dados['g-0'].unique())

dados['g-0'].max()

dados['g-0'].hist(bins = 100)

dados['g-19'].hist(bins = 100)

dados['g-0'].mean()

dados.describe()

dados.loc[:,'g-0':'g-71'].describe()

dados.loc[:,'g-0':'g-771'].describe().T['mean'].hist(bins=50) #transformar linhas em colunas

dados.loc[:,'g-0':'g-771'].describe().T['min'].hist(bins=50)

dados.loc[:,'g-0':'g-771'].describe().T['max'].hist(bins=50)

dados.loc[:,'c-0':'c-99'].describe().T['mean'].hist(bins=50)

sns.boxplot(x = 'g-0', data = dados)

sns.boxplot(x = 'g-0', y = 'tratamento',data = dados)

sns.boxplot(x = 'tratamento', y = 'g-0',data = dados)