# -*- coding: utf-8 -*-
"""aula_03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MkhhU6flQSUDEF1LG7ZwnU3mMJThpRmr
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

url_dados = 'https://github.com/alura-cursos/imersaodados3/blob/main/dados/dados_experimentos.zip?raw=true'
dados = pd.read_csv(url_dados, compression='zip')#compression para abrir um arquivo zip

dados.head()

pd.crosstab(dados['dose'], dados['tempo'])

pd.crosstab([dados['dose'], dados['tempo']],dados['tratamento'])

pd.crosstab([dados['dose'], dados['tempo']],dados['tratamento'],normalize='index')
agrupado = dados.groupby(['dose','tempo','tratamento']).size()
agrupado

pd.crosstab([dados['dose'], dados['tempo']],dados['tratamento'], values=dados['g-0'], aggfunc='mean')

dados[['g-0', 'g-3nb  ']]

sns.scatterplot(x='g-0', y = 'g-3', data=dados)

sns.scatterplot(x='g-0', y = 'g-8', data=dados)

sns.lmplot(data=dados, x = 'g-0', y = 'g-8', line_kws={'color':'red'}, col = 'tratamento', row='tempo')

dados.loc[:,'g-0':'g-771'].corr()

# Compute the correlation matrix
corr = dados.loc[:,'g-0':'g-50'].corr()

# Generate a mask for the upper triangle
mask = np.triu(np.ones_like(corr, dtype=bool))

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(11, 9))

# Generate a custom diverging colormap
cmap = sns.diverging_palette(230, 20, as_cmap=True)

# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr, mask=mask, cmap=cmap,  center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5})

# Compute the correlation matrix
corr = dados.loc[:,'c-0':'c-50'].corr()

# Generate a mask for the upper triangle
mask = np.triu(np.ones_like(corr, dtype=bool))

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(11, 9))

# Generate a custom diverging colormap
cmap = sns.diverging_palette(230, 20, as_cmap=True)

# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr, mask=mask, cmap=cmap,  center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5})