# -*- coding: utf-8 -*-
"""aula_04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1prm0Q9xfb7zcPr7BTxkM2vGjUPhPD30P
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

url_dados = 'https://github.com/alura-cursos/imersaodados3/blob/main/dados/dados_experimentos.zip?raw=true'
dados = pd.read_csv(url_dados, compression='zip')#compression para abrir um arquivo zip
url_dados_2 = 'https://github.com/alura-cursos/imersao-dados-desafio-final/blob/main/Dados/dados_resultados.csv?raw=true'
dados_resultados = pd.read_csv(url_dados_2)#compression para abrir um arquivo zip
dados_resultados.head()

dados_resultados['acetylcholine_receptor_agonist'].unique()

contagem_moa = dados_resultados.select_dtypes('int64').sum().sort_values(ascending=False)
contagem_moa

dados_resultados.drop('id', axis=1).sum(axis = 1)

dados_resultados['n_moa'] = dados_resultados.drop('id', axis=1).sum(axis = 1)

dados_resultados.head()

dados_resultados['ativo_moa'] = (dados_resultados['n_moa'] != 0)

dados_resultados.head()

dados_combinados = pd.merge(dados, dados_resultados[['id','n_moa', 'ativo_moa']], on='id')
dados_combinados.head()

dados_combinados.query('tratamento == "com_controle"')['ativo_moa'].value_counts()

dados_combinados.query('tratamento == "com_droga"')['ativo_moa'].value_counts()

composto_principal  =  dados_combinados['droga'].value_counts().index[:5]
print(composto_principal)
composto_principal_query = dados_combinados.query('droga in @composto_principal')
sns.boxplot(data = composto_principal_query, y = 'g-0', x = 'droga', hue = 'ativo_moa')

dados.head()